export enum Planet {
    SUN = 1,
    MOON = 2,
    MARS = 3,
    MERCURY = 4,
    JUPITER = 5,
    VENUS = 6,
    SATURN = 7,
    RAHU = 8,
    KETU = 9,
}

export enum ZodiacSign {
    ARIES = 1,
    TAURUS = 2,
    GEMINI = 3,
    CANCER = 4,
    LEO = 5,
    VIRGO = 6,
    LIBRA = 7,
    SCORPIO = 8,
    SAGITTARIUS = 9,
    CAPRICORN = 10,
    AQUARIUS = 11,
    PISCES = 12,
}

export const PLANET_NAMES: Record<string, Planet> = {
    රවි: Planet.SUN,
    ඉර: Planet.SUN,
    sun: Planet.SUN,
    surya: Planet.SUN,
    ravi: Planet.SUN,
    සඳු: Planet.MOON,
    හඳ: Planet.MOON,
    සඳ: Planet.MOON,
    moon: Planet.MOON,
    chandra: Planet.MOON,
    කුජ: Planet.MARS,
    mars: Planet.MARS,
    අඟහරු: Planet.MARS,
    mangal: Planet.MARS,
    mangala: Planet.MARS,
    kuja: Planet.MARS,
    බුධ: Planet.MERCURY,
    බුද: Planet.MERCURY,
    mercury: Planet.MERCURY,
    budha: Planet.MERCURY,
    budh: Planet.MERCURY,
    ගුරු: Planet.JUPITER,
    jupiter: Planet.JUPITER,
    guru: Planet.JUPITER,
    brihaspati: Planet.JUPITER,
    brhaspati: Planet.JUPITER,
    ශුක්‍ර: Planet.VENUS,
    සිකුරු: Planet.VENUS,
    venus: Planet.VENUS,
    shukra: Planet.VENUS,
    sukra: Planet.VENUS,
    ශනි: Planet.SATURN,
    saturn: Planet.SATURN,
    shani: Planet.SATURN,
    sani: Planet.SATURN,
    රාහු: Planet.RAHU,
    rahu: Planet.RAHU,
    කේතු: Planet.KETU,
    ketu: Planet.KETU,
};

export enum PlanetaryStrength {
    ATHI_UCHCHA = 1.25,
    UCHCHA = 1,
    NEECHA = -1,
    ATHI_NEECHA = -1.25,
    MOOLATRIKONA = 0.75,
    OWN_SIGN = 0.5,
    MITRA = 0.1,
    SHATRU = -0.1,
    SAMA = 0,
}

export const STRENGTH_LABELS: Record<string, PlanetaryStrength> = {
    උච්ච: PlanetaryStrength.UCHCHA,
    උච්චව: PlanetaryStrength.UCHCHA,
    උච්චත්වය: PlanetaryStrength.UCHCHA,
    exaltation: PlanetaryStrength.UCHCHA,
    exalted: PlanetaryStrength.UCHCHA,
    uchcha: PlanetaryStrength.UCHCHA,
    "අති උච්ච": PlanetaryStrength.ATHI_UCHCHA,
    "athi uchcha": PlanetaryStrength.ATHI_UCHCHA,
    "very exalted": PlanetaryStrength.ATHI_UCHCHA,
    නීච: PlanetaryStrength.NEECHA,
    නීචව: PlanetaryStrength.NEECHA,
    නීචත්වය: PlanetaryStrength.NEECHA,
    debilitation: PlanetaryStrength.NEECHA,
    debilitated: PlanetaryStrength.NEECHA,
    neecha: PlanetaryStrength.NEECHA,
    "අති නීච": PlanetaryStrength.ATHI_NEECHA,
    "athi neecha": PlanetaryStrength.ATHI_NEECHA,
    "very debilitated": PlanetaryStrength.ATHI_NEECHA,
    moolatrikona: PlanetaryStrength.MOOLATRIKONA,
    මූලත්‍රිකෝණ: PlanetaryStrength.MOOLATRIKONA,
    "own sign": PlanetaryStrength.OWN_SIGN,
    "ස්ව රාශි": PlanetaryStrength.OWN_SIGN,
    ස්වක්ෂේත්‍ර: PlanetaryStrength.OWN_SIGN,
    mitra: PlanetaryStrength.MITRA,
    මිත්‍ර: PlanetaryStrength.MITRA,
    මිතුරු: PlanetaryStrength.MITRA,
    "friend sign": PlanetaryStrength.MITRA,
    shatru: PlanetaryStrength.SHATRU,
    සතුරු: PlanetaryStrength.SHATRU,
    ශත්‍රැ: PlanetaryStrength.SHATRU,
    "enemy sign": PlanetaryStrength.SHATRU,
    sama: PlanetaryStrength.SAMA,
    සම: PlanetaryStrength.SAMA,
    neutral: PlanetaryStrength.SAMA,
};

export const PLANET_LABELS_EN: Record<number, string> = {
    1: "Sun",
    2: "Moon",
    3: "Mars",
    4: "Mercury",
    5: "Jupiter",
    6: "Venus",
    7: "Saturn",
    8: "Rahu",
    9: "Ketu",
};

export const PLANET_LABELS_SI: Record<number, string> = {
    1: "රවි",
    2: "සඳු",
    3: "කුජ",
    4: "බුධ",
    5: "ගුරු",
    6: "සිකුරු",
    7: "ශනි",
    8: "රාහු",
    9: "කේතු",
};

export const COMBUSTION_ORBS: Record<number, number> = {
    [Planet.MOON]: 12,
    [Planet.MARS]: 17,
    [Planet.MERCURY]: 14,
    [Planet.JUPITER]: 11,
    [Planet.VENUS]: 10,
    [Planet.SATURN]: 16,
};

export const STRENGTH_DISPLAY_EN: Record<string, string> = {
    [PlanetaryStrength.ATHI_UCHCHA]: "Athi Uchcha (very exalted)",
    AthiUchcha: "Athi Uchcha (very exalted)",
    [PlanetaryStrength.UCHCHA]: "Uchcha (exalted)",
    Uchcha: "Uchcha (exalted)",
    [PlanetaryStrength.NEECHA]: "Neecha (debilitated)",
    Neecha: "Neecha (debilitated)",
    [PlanetaryStrength.ATHI_NEECHA]: "Athi Neecha (very debilitated)",
    AthiNeecha: "Athi Neecha (very debilitated)",
    [PlanetaryStrength.MOOLATRIKONA]: "Moolatrikona",
    Moolatrikona: "Moolatrikona",
    [PlanetaryStrength.OWN_SIGN]: "own sign",
    OwnSign: "own sign",
    [PlanetaryStrength.MITRA]: "friend sign",
    Mitra: "friend sign",
    [PlanetaryStrength.SHATRU]: "enemy sign",
    Shatru: "enemy sign",
    [PlanetaryStrength.SAMA]: "neutral",
    Sama: "neutral",
};

export const STRENGTH_DISPLAY_SI: Record<string, string> = {
    [PlanetaryStrength.ATHI_UCHCHA]: "අති උච්ච",
    AthiUchcha: "අති උච්ච",
    [PlanetaryStrength.UCHCHA]: "උච්ච",
    Uchcha: "උච්ච",
    [PlanetaryStrength.NEECHA]: "නීච",
    Neecha: "නීච",
    [PlanetaryStrength.ATHI_NEECHA]: "අති නීච",
    AthiNeecha: "අති නීච",
    [PlanetaryStrength.MOOLATRIKONA]: "මූලත්‍රිකෝණ",
    Moolatrikona: "මූලත්‍රිකෝණ",
    [PlanetaryStrength.OWN_SIGN]: "ස්ව රාශි",
    OwnSign: "ස්ව රාශි",
    [PlanetaryStrength.MITRA]: "මිත්‍ර",
    Mitra: "මිත්‍ර",
    [PlanetaryStrength.SHATRU]: "ශත්‍රැ",
    Shatru: "ශත්‍රැ",
    [PlanetaryStrength.SAMA]: "සම",
    Sama: "සම",
};

export enum PanchaPakshi {
    VULTURE = 1,
    OWL = 2,
    CROW = 3,
    COCK = 4,
    PEACOCK = 5,
}

export enum Nakshatra {
    ASHWINI = 1,
    BHARANI = 2,
    KRITTIKA = 3,
    ROHINI = 4,
    MRIGASHIRA = 5,
    ARDRA = 6,
    PUNARVASU = 7,
    PUSHYA = 8,
    ASHLESHA = 9,
    MAGHA = 10,
    PURVA_PHALGUNI = 11,
    UTTARA_PHALGUNI = 12,
    HASTA = 13,
    CHITRA = 14,
    SWATI = 15,
    VISHAKHA = 16,
    ANURADHA = 17,
    JYESHTHA = 18,
    MULA = 19,
    PURVA_ASHADHA = 20,
    UTTARA_ASHADHA = 21,
    SHRAVANA = 22,
    DHANISHTA = 23,
    SHATABHISHA = 24,
    PURVA_BHADRAPADA = 25,
    UTTARA_BHADRAPADA = 26,
    REVATI = 27,
}

export const NAKSHATRA_NAMES: Record<string, Nakshatra> = {
    අශ්විනි: Nakshatra.ASHWINI,
    ashwini: Nakshatra.ASHWINI,
    භරණී: Nakshatra.BHARANI,
    bharani: Nakshatra.BHARANI,
    කෘත්තිකා: Nakshatra.KRITTIKA,
    krittika: Nakshatra.KRITTIKA,
    රෝහිණී: Nakshatra.ROHINI,
    rohini: Nakshatra.ROHINI,
    මෘගශීර්ෂ: Nakshatra.MRIGASHIRA,
    mrigashira: Nakshatra.MRIGASHIRA,
    ආර්ද්‍රා: Nakshatra.ARDRA,
    ardra: Nakshatra.ARDRA,
    පුනර්වසු: Nakshatra.PUNARVASU,
    punarvasu: Nakshatra.PUNARVASU,
    පුෂ්‍ය: Nakshatra.PUSHYA,
    pushya: Nakshatra.PUSHYA,
    ආශ්ලේෂා: Nakshatra.ASHLESHA,
    ashlesha: Nakshatra.ASHLESHA,
    මාඝ: Nakshatra.MAGHA,
    magha: Nakshatra.MAGHA,
    "පූර්ව ඵල්ගුනී": Nakshatra.PURVA_PHALGUNI,
    "purva phalguni": Nakshatra.PURVA_PHALGUNI,
    "උත්තර ඵල්ගුනී": Nakshatra.UTTARA_PHALGUNI,
    "uttara phalguni": Nakshatra.UTTARA_PHALGUNI,
    හස්ත: Nakshatra.HASTA,
    hasta: Nakshatra.HASTA,
    චිත්‍රා: Nakshatra.CHITRA,
    chitra: Nakshatra.CHITRA,
    ස්වාති: Nakshatra.SWATI,
    swati: Nakshatra.SWATI,
    විශාඛා: Nakshatra.VISHAKHA,
    vishakha: Nakshatra.VISHAKHA,
    අනුරාධා: Nakshatra.ANURADHA,
    anuradha: Nakshatra.ANURADHA,
    ජ්‍යෙෂ්ඨා: Nakshatra.JYESHTHA,
    jyeshtha: Nakshatra.JYESHTHA,
    මූල: Nakshatra.MULA,
    mula: Nakshatra.MULA,
    "පූර්ව ආෂාඪ": Nakshatra.PURVA_ASHADHA,
    "purva ashadha": Nakshatra.PURVA_ASHADHA,
    "උත්තර ආෂාඪ": Nakshatra.UTTARA_ASHADHA,
    "uttara ashadha": Nakshatra.UTTARA_ASHADHA,
    ශ්‍රවණ: Nakshatra.SHRAVANA,
    shravana: Nakshatra.SHRAVANA,
    ධනිෂ්ඨා: Nakshatra.DHANISHTA,
    dhanishta: Nakshatra.DHANISHTA,
    ශතභිෂා: Nakshatra.SHATABHISHA,
    shatabhisha: Nakshatra.SHATABHISHA,
    "පූර්ව භාද්‍රපද": Nakshatra.PURVA_BHADRAPADA,
    "purva bhadrapada": Nakshatra.PURVA_BHADRAPADA,
    "උත්තර භාද්‍රපද": Nakshatra.UTTARA_BHADRAPADA,
    "uttara bhadrapada": Nakshatra.UTTARA_BHADRAPADA,
    රේවතී: Nakshatra.REVATI,
    revati: Nakshatra.REVATI,
    අස්විද: Nakshatra.ASHWINI,
    බෙරණ: Nakshatra.BHARANI,
    කැති: Nakshatra.KRITTIKA,
    රෙහෙණ: Nakshatra.ROHINI,
    මුවසිරිස: Nakshatra.MRIGASHIRA,
    අද: Nakshatra.ARDRA,
    පුනාවස: Nakshatra.PUNARVASU,
    පුස: Nakshatra.PUSHYA,
    අස්ලිස: Nakshatra.ASHLESHA,
    අස්ලිය: Nakshatra.ASHLESHA,
    මා: Nakshatra.MAGHA,
    පුවපල්: Nakshatra.PURVA_PHALGUNI,
    උත්‍රපල්: Nakshatra.UTTARA_PHALGUNI,
    හත: Nakshatra.HASTA,
    සිත: Nakshatra.CHITRA,
    සා: Nakshatra.SWATI,
    විසා: Nakshatra.VISHAKHA,
    අනුර: Nakshatra.ANURADHA,
    දෙට: Nakshatra.JYESHTHA,
    පුවසල: Nakshatra.PURVA_ASHADHA,
    උත්‍රසල: Nakshatra.UTTARA_ASHADHA,
    සුවන: Nakshatra.SHRAVANA,
    දෙනට: Nakshatra.DHANISHTA,
    සියාවස: Nakshatra.SHATABHISHA,
    පුවපුටුප: Nakshatra.PURVA_BHADRAPADA,
    උත්‍රපුටුප: Nakshatra.UTTARA_BHADRAPADA,
};

export const NAKSHATRA_LABELS_EN: Record<number, string> = {
    1: "Ashwini",
    2: "Bharani",
    3: "Krittika",
    4: "Rohini",
    5: "Mrigashira",
    6: "Ardra",
    7: "Punarvasu",
    8: "Pushya",
    9: "Ashlesha",
    10: "Magha",
    11: "Purva Phalguni",
    12: "Uttara Phalguni",
    13: "Hasta",
    14: "Chitra",
    15: "Swati",
    16: "Vishakha",
    17: "Anuradha",
    18: "Jyeshtha",
    19: "Mula",
    20: "Purva Ashadha",
    21: "Uttara Ashadha",
    22: "Shravana",
    23: "Dhanishta",
    24: "Shatabhisha",
    25: "Purva Bhadrapada",
    26: "Uttara Bhadrapada",
    27: "Revati",
};

export const NAKSHATRA_LABELS_SI: Record<number, string> = {
    1: "අශ්විනි",
    2: "භරණී",
    3: "කෘත්තිකා",
    4: "රෝහිණී",
    5: "මෘගශීර්ෂ",
    6: "ආර්ද්‍රා",
    7: "පුනර්වසු",
    8: "පුෂ්‍ය",
    9: "ආශ්ලේෂා",
    10: "මාඝ",
    11: "පූර්ව ඵල්ගුනී",
    12: "උත්තර ඵල්ගුනී",
    13: "හස්ත",
    14: "චිත්‍රා",
    15: "ස්වාති",
    16: "විශාඛා",
    17: "අනුරාධා",
    18: "ජ්‍යෙෂ්ඨා",
    19: "මූල",
    20: "පූර්ව ආශාඩ්",
    21: "උත්තර ආශාඩ්",
    22: "ශ්‍රවණ",
    23: "ධනිෂ්ඨා",
    24: "ශතභිෂා",
    25: "පූර්ව භාද්‍රපදා",
    26: "උත්තර භාද්‍රපදා",
    27: "රේවතී",
};

export const NAKSHATRA_COLLOQUIAL_KEYS = new Set<string>([
    "අස්විද",
    "බෙරණ",
    "කැති",
    "රෙහෙණ",
    "මුවසිරිස",
    "අද",
    "පුනාවස",
    "පුස",
    "අස්ලිස",
    "අස්ලිය",
    "මා",
    "පුවපල්",
    "උත්‍රපල්",
    "හත",
    "සිත",
    "සා",
    "විසා",
    "අනුර",
    "දෙට",
    "පුවසල",
    "උත්‍රසල",
    "සුවන",
    "දෙනට",
    "සියාවස",
    "පුවපුටුප",
    "උත්‍රපුටුප",
]);

export const ZODIAC_SIGN_NAMES: Record<string, ZodiacSign> = {
    මේෂ: ZodiacSign.ARIES,
    aries: ZodiacSign.ARIES,
    mesha: ZodiacSign.ARIES,
    mhesha: ZodiacSign.ARIES,
    වෘෂභ: ZodiacSign.TAURUS,
    taurus: ZodiacSign.TAURUS,
    vrushabha: ZodiacSign.TAURUS,
    vrishabha: ZodiacSign.TAURUS,
    වෘෂභය: ZodiacSign.TAURUS,
    මිථුන: ZodiacSign.GEMINI,
    gemini: ZodiacSign.GEMINI,
    mithuna: ZodiacSign.GEMINI,
    mithun: ZodiacSign.GEMINI,
    කටක: ZodiacSign.CANCER,
    cancer: ZodiacSign.CANCER,
    karka: ZodiacSign.CANCER,
    karkata: ZodiacSign.CANCER,
    සිංහ: ZodiacSign.LEO,
    leo: ZodiacSign.LEO,
    simha: ZodiacSign.LEO,
    sinhha: ZodiacSign.LEO,
    කන්යා: ZodiacSign.VIRGO,
    virgo: ZodiacSign.VIRGO,
    kanya: ZodiacSign.VIRGO,
    තුලා: ZodiacSign.LIBRA,
    libra: ZodiacSign.LIBRA,
    tula: ZodiacSign.LIBRA,
    වෘශ්චික: ZodiacSign.SCORPIO,
    scorpio: ZodiacSign.SCORPIO,
    vruschika: ZodiacSign.SCORPIO,
    vrischika: ZodiacSign.SCORPIO,
    ධනු: ZodiacSign.SAGITTARIUS,
    sagittarius: ZodiacSign.SAGITTARIUS,
    dhanu: ZodiacSign.SAGITTARIUS,
    dhanus: ZodiacSign.SAGITTARIUS,
    මකර: ZodiacSign.CAPRICORN,
    capricorn: ZodiacSign.CAPRICORN,
    makara: ZodiacSign.CAPRICORN,
    makaram: ZodiacSign.CAPRICORN,
    කුම්භ: ZodiacSign.AQUARIUS,
    aquarius: ZodiacSign.AQUARIUS,
    kumbha: ZodiacSign.AQUARIUS,
    kumbh: ZodiacSign.AQUARIUS,
    මීන: ZodiacSign.PISCES,
    pisces: ZodiacSign.PISCES,
    meena: ZodiacSign.PISCES,
    meen: ZodiacSign.PISCES,
    mina: ZodiacSign.PISCES,
};

export const ZODIAC_SIGN_LABELS_EN: Record<number, string> = {
    1: "Aries",
    2: "Taurus",
    3: "Gemini",
    4: "Cancer",
    5: "Leo",
    6: "Virgo",
    7: "Libra",
    8: "Scorpio",
    9: "Sagittarius",
    10: "Capricorn",
    11: "Aquarius",
    12: "Pisces",
};

export const ZODIAC_SIGN_LABELS_SI: Record<number, string> = {
    1: "මේෂ",
    2: "වෘෂභ",
    3: "මිථුන",
    4: "කටක",
    5: "සිංහ",
    6: "කන්යා",
    7: "තුලා",
    8: "වෘශ්චික",
    9: "ධනු",
    10: "මකර",
    11: "කුම්භ",
    12: "මීන",
};

export const THITHI_LABELS_EN: Record<number, string> = {
    1: "Shukla Pratipada",
    2: "Shukla Dwitiya",
    3: "Shukla Tritiya",
    4: "Shukla Chaturthi",
    5: "Shukla Panchami",
    6: "Shukla Shashthi",
    7: "Shukla Saptami",
    8: "Shukla Ashtami",
    9: "Shukla Navami",
    10: "Shukla Dashami",
    11: "Shukla Ekadashi",
    12: "Shukla Dwadashi",
    13: "Shukla Trayodashi",
    14: "Shukla Chaturdashi",
    15: "Purnima",
    16: "Krishna Pratipada",
    17: "Krishna Dwitiya",
    18: "Krishna Tritiya",
    19: "Krishna Chaturthi",
    20: "Krishna Panchami",
    21: "Krishna Shashthi",
    22: "Krishna Saptami",
    23: "Krishna Ashtami",
    24: "Krishna Navami",
    25: "Krishna Dashami",
    26: "Krishna Ekadashi",
    27: "Krishna Dwadashi",
    28: "Krishna Trayodashi",
    29: "Krishna Chaturdashi",
    30: "Amavasya",
};

export const THITHI_LABELS_SI: Record<number, string> = {
    1: "පුර පෑලවිය",
    2: "පුර දියවක",
    3: "පුර තියවක",
    4: "පුර ජලවක",
    5: "පුර පසවක",
    6: "පුර සැටවක",
    7: "පුර සතවක",
    8: "පුර අටවක",
    9: "පුර නවවක",
    10: "පුර දසවක",
    11: "පුර එකොළොස්වක",
    12: "පුර දොළොස්වක",
    13: "පුර තෙළෙස්වක",
    14: "පුර තුදුස්වක",
    15: "පුර පසළොස්වක",
    16: "අව පෑලවිය",
    17: "අව දියවක",
    18: "අව තියවක",
    19: "අව ජලවක",
    20: "අව පසවක",
    21: "අව සැටවක",
    22: "අව සතවක",
    23: "අව අටවක",
    24: "අව නවවක",
    25: "අව දසවක",
    26: "අව එකොළොස්වක",
    27: "අව දොළොස්වක",
    28: "අව තෙළෙස්වක",
    29: "අව තුදුස්වක",
    30: "අමාවක",
};
