export enum Planet {
    SUN = 1,
    MOON = 2,
    MARS = 3,
    MERCURY = 4,
    JUPITER = 5,
    VENUS = 6,
    SATURN = 7,
    RAHU = 8,
    KETU = 9,
}

export enum ZodiacSign {
    ARIES = 1,
    TAURUS = 2,
    GEMINI = 3,
    CANCER = 4,
    LEO = 5,
    VIRGO = 6,
    LIBRA = 7,
    SCORPIO = 8,
    SAGITTARIUS = 9,
    CAPRICORN = 10,
    AQUARIUS = 11,
    PISCES = 12,
}

export const PLANET_NAMES: Record<string, Planet> = {
    රවි: Planet.SUN,
    ඉර: Planet.SUN,
    sun: Planet.SUN,
    සඳු: Planet.MOON,
    හඳ: Planet.MOON,
    සඳ: Planet.MOON,
    moon: Planet.MOON,
    කුජ: Planet.MARS,
    mars: Planet.MARS,
    අඟහරු: Planet.MARS,
    බුධ: Planet.MERCURY,
    බුද: Planet.MERCURY,
    mercury: Planet.MERCURY,
    ගුරු: Planet.JUPITER,
    jupiter: Planet.JUPITER,
    ශුක්‍ර: Planet.VENUS,
    සිකුරු: Planet.VENUS,
    venus: Planet.VENUS,
    ශනි: Planet.SATURN,
    saturn: Planet.SATURN,
    රාහු: Planet.RAHU,
    rahu: Planet.RAHU,
    කේතු: Planet.KETU,
    ketu: Planet.KETU,
};

export enum PlanetaryStrength {
    ATHI_UCHCHA = "AthiUchcha",
    UCHCHA = "Uchcha",
    NEECHA = "Neecha",
    ATHI_NEECHA = "AthiNeecha",
    MOOLATRIKONA = "Moolatrikona",
    OWN_SIGN = "OwnSign",
    MITRA = "Mitra",
    SHATRU = "Shatru",
    SAMA = "Sama",
}

export const COMBUSTION_ORBS: Record<number, number> = {
    [Planet.MOON]: 12,
    [Planet.MARS]: 17,
    [Planet.MERCURY]: 14,
    [Planet.JUPITER]: 11,
    [Planet.VENUS]: 10,
    [Planet.SATURN]: 16,
};

export const ZODIAC_SIGN_NAMES: Record<string, ZodiacSign> = {
    මේෂ: ZodiacSign.ARIES,
    aries: ZodiacSign.ARIES,
    වෘෂභ: ZodiacSign.TAURUS,
    taurus: ZodiacSign.TAURUS,
    මිථුන: ZodiacSign.GEMINI,
    gemini: ZodiacSign.GEMINI,
    කටක: ZodiacSign.CANCER,
    cancer: ZodiacSign.CANCER,
    සිංහ: ZodiacSign.LEO,
    leo: ZodiacSign.LEO,
    කන්යා: ZodiacSign.VIRGO,
    virgo: ZodiacSign.VIRGO,
    තුලා: ZodiacSign.LIBRA,
    libra: ZodiacSign.LIBRA,
    වෘශ්චික: ZodiacSign.SCORPIO,
    scorpio: ZodiacSign.SCORPIO,
    ධනු: ZodiacSign.SAGITTARIUS,
    sagittarius: ZodiacSign.SAGITTARIUS,
    මකර: ZodiacSign.CAPRICORN,
    capricorn: ZodiacSign.CAPRICORN,
    කුම්භ: ZodiacSign.AQUARIUS,
    aquarius: ZodiacSign.AQUARIUS,
    මීන: ZodiacSign.PISCES,
    pisces: ZodiacSign.PISCES,
};
