import { resolve } from 'path';
import { writeFileSync, mkdirSync, readdirSync, statSync } from 'fs';
import * as TJS from 'typescript-json-schema';

const basePath = resolve(__dirname, '..');
const typesDir = resolve(basePath, 'src/types');

const collectFiles = (dir: string): string[] => {
  const entries: string[] = [];
  readdirSync(dir).forEach((name) => {
    const full = resolve(dir, name);
    if (statSync(full).isDirectory()) {
      entries.push(...collectFiles(full));
    } else if (name.endsWith('.ts')) {
      entries.push(full);
    }
  });
  return entries;
};

const typeFiles = collectFiles(typesDir);
const compilerOptions: TJS.CompilerOptions = {
  strictNullChecks: true,
  esModuleInterop: true,
  allowSyntheticDefaultImports: true,
};
const program = TJS.getProgramFromFiles(typeFiles, compilerOptions, basePath);

const generator = TJS.buildGenerator(program, { required: true });
if (!generator) throw new Error('Failed to build schema generator');

const typeChecker = program.getTypeChecker();
const sourceFiles = new Set(typeFiles.map((f) => f.replace(/\\/g, '/')));

const ownSymbols = new Set<string>();
program.getSourceFiles().forEach((sf) => {
  if (!sourceFiles.has(sf.fileName.replace(/\\/g, '/'))) return;
  typeChecker.getExportsOfModule(typeChecker.getSymbolAtLocation(sf)!).forEach((s) => {
    ownSymbols.add(s.getName());
  });
});

const requestSettings: TJS.PartialArgs = { required: true, noExtraProps: true };
const responseSettings: TJS.PartialArgs = { required: true };

const lines: string[] = [
  '// Auto-generated by scripts/generateSchemas.ts — do not edit',
  '/* eslint-disable */',
];

ownSymbols.forEach((symbol) => {
  if (symbol.endsWith('Body')) {
    const schema = TJS.generateSchema(program, symbol, requestSettings);
    const exportName = `${symbol.charAt(0).toLowerCase()}${symbol.slice(1)}Schema`;
    lines.push(`\nexport const ${exportName} = ${JSON.stringify(schema, null, 2)} as const;`);
  } else if (symbol.endsWith('Data')) {
    const schema = TJS.generateSchema(program, symbol, responseSettings);
    const exportName = `${symbol.charAt(0).toLowerCase()}${symbol.slice(1)}Schema`;
    lines.push(`\nexport const ${exportName} = ${JSON.stringify(schema, null, 2)} as const;`);
  }
});

mkdirSync(resolve(basePath, 'src/schemas'), { recursive: true });
writeFileSync(resolve(basePath, 'src/schemas/generated.ts'), lines.join('\n') + '\n');
